version: '3.9'
services:
  notes_frontend:
    image: notes-frontend
    build:
      context: ./notes-frontend
      dockerfile: Dockerfile
    container_name: notes-frontend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - api_backend
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://api_backend:8000/api
    # networks:
    #   - notes-network

  api_backend:
    image: api-backend
    build:
      context: ./api-backend
      dockerfile: Dockerfile
    container_name: api-backend
    expose:
      - "8000"
    # networks:
    #   - notes-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_backend
      - notes_frontend

# networks:
#   notes-network:
#     driver: bridge