version: '3.8'
services:
  frontend:
    image: notes-frontend
    build: ./notes-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:80
    # networks:
    #   - notes-network

  backend:
    image: api-backend
    build: ./api-backend
    ports:
      - "8000:80"
    # networks:
    #   - notes-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

# networks:
#   notes-network:
#     driver: bridge