"""set Folder.name.unique=False

Revision ID: 334a6dfb97b7
Revises: 1f65e459e15e
Create Date: 2025-07-07 14:49:19.836692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334a6dfb97b7'
down_revision: Union[str, None] = '1f65e459e15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_folders_name', 'folders', type_='unique')
    # ### end Alembic commands ###
    with op.batch_alter_table("folders", schema=None) as batch_op:
        batch_op.drop_constraint('uq_folders_name', type_='unique')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_folders_name', 'folders', ['name'])
    # ### end Alembic commands ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_folders_name', ['name'])
