"""Added attribute unique=True to models Tag.name & Folder.name

Revision ID: 5e75e3217a06
Revises: de0bade9606d
Create Date: 2025-07-02 14:47:15.879928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e75e3217a06'
down_revision: Union[str, None] = 'de0bade9606d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        # op.create_unique_constraint(None, 'folders', ['name'])
        batch_op.create_unique_constraint('uq_folders_name', ['name'])

    with op.batch_alter_table('tags', schema=None) as batch_op:
        # op.create_unique_constraint(None, 'tags', ['name'])
        batch_op.create_unique_constraint('uq_tags_name', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        # op.drop_constraint(None, 'tags', type_='unique')
        batch_op.drop_constraint('uq_folders_name', type_='unique')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        # op.drop_constraint(None, 'folders', type_='unique')
        batch_op.drop_constraint('uq_tags_name', type_='unique')
        
    # ### end Alembic commands ###
