"""Added models- Tag, Folder, note_tag_association

Revision ID: de0bade9606d
Revises: b146e0c16665
Create Date: 2025-07-01 14:17:25.007261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'de0bade9606d'
down_revision: Union[str, None] = 'b146e0c16665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_tags',
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.add_column('notes', sa.Column('folder_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('notes') as batch_op:
        # batch_op.create_foreign_key(None, 'folders', ['folder_id'], ['id'])
        batch_op.create_foreign_key('fk_notes_folder_id_folders', 'folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes') as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_notes_folder_id_folders', type_='foreignkey')
    
    op.drop_column('notes', 'folder_id')
    op.drop_table('note_tags')
    op.drop_table('tags')
    op.drop_table('folders')
    # ### end Alembic commands ###
